[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swns = "webrAiEmdFtimWnVBjbYbsezPiQAThwBmNvtN4agEH2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aditya/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
